### ISSUE TITLE
Scala 3 Support

### ISSUE THREAD

**Issue by froth** [sfxcode/pebble-scala#18]
As we are currently in the decision process for choosing a new template language:

Are you planning on migrating this library to scala 3?

**Comment by sfxcode** [comment]
Since there is only the specs2 dependency without actual 3.0.0-M3 support,
I used the 2.13 version of specs 2 actually and released a new Version 0.9.0,
which supports Dotty 3.0.0-M3.

@froth 
In my company we use this library for Mail Templating and other stuff without problems.
Pebble is the best choice for templates with scala in my oppinion.

Regards,

Tom

**Comment by froth** [comment]
Nice, thanks!

Greetings,

Fred
